# Generated by Django 4.2.7 on 2023-11-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registered_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь библиотеки',
                'verbose_name_plural': 'Пользователи библиотеки',
                'ordering': ['registered_at'],
            },
        ),
    ]
